import javax.swing.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class Practice3 extends javax.swing.JFrame {
    String s1,pra,name2,ID;
    int error,record;
    
    public Practice3(String st1,String practice,int rec,int err,String ID2,String name) {
        pra=practice;
        name2=name;
        record=rec+1;
        ID=ID2;
        error=err;
        s1=st1;        
        initComponents();               
        for(Component cas:Group2.getComponents())
        {            
            if(cas instanceof JTextField)
            {                
                JTextField temp=(JTextField)cas;
                temp.setTransferHandler(null);                   
            }                       
        }       
        element1fld1.setFocusable(true);        
        element1fld1.setNextFocusableComponent(element3fld4);    
        element3fld4.setNextFocusableComponent(element5fld6);    
        element5fld6.setNextFocusableComponent(element6lbl7);
        element6lbl7.setNextFocusableComponent(element9lbl10);        
        mytitle.setText(practice);
        Racordlbl1.setText(String.valueOf(record));
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Group2 = new javax.swing.JPanel();
        element11 = new javax.swing.JLabel();
        element1fld1 = new javax.swing.JTextField();
        element13 = new javax.swing.JLabel();
        element3fld4 = new javax.swing.JTextField();
        element15 = new javax.swing.JLabel();
        element5fld6 = new javax.swing.JTextField();
        element16 = new javax.swing.JLabel();
        element6lbl7 = new javax.swing.JTextField();
        element19 = new javax.swing.JLabel();
        element9lbl10 = new javax.swing.JTextField();
        force = new javax.swing.JPanel();
        forcestop = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        mytitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Racordlbl = new javax.swing.JLabel();
        Errorelbl = new javax.swing.JLabel();
        Racordlbl1 = new javax.swing.JLabel();
        errorlbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(230, 230, 230));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(25, 35, 55)));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        Group2.setBackground(new java.awt.Color(230, 230, 230));

        element11.setFont(new getfont().getone(Font.BOLD,16f));
        element11.setForeground(new java.awt.Color(102, 153, 255));
        element11.setText("The quick brown fox jumps over the lazy dog.");

        element1fld1.setBackground(new java.awt.Color(230, 230, 230));
        element1fld1.setFont(new getfont().getone(Font.BOLD,20f));
        element1fld1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 153, 255)));
        element1fld1.setFocusable(false);
        element1fld1.setMaximumSize(new java.awt.Dimension(0, 17));
        element1fld1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                controlfld(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                controlfld(evt);
            }
        });

        element13.setFont(new getfont().getone(Font.BOLD,16f));
        element13.setForeground(new java.awt.Color(102, 153, 255));
        element13.setText("The quick brown fox jumps over the lazy dog.");

        element3fld4.setBackground(new java.awt.Color(230, 230, 230));
        element3fld4.setFont(new getfont().getone(Font.BOLD,20f));
        element3fld4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 153, 255)));
        element3fld4.setFocusable(false);
        element3fld4.setMaximumSize(new java.awt.Dimension(0, 17));
        element3fld4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                controlfld(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                controlfld(evt);
            }
        });

        element15.setFont(new getfont().getone(Font.BOLD,16f));
        element15.setForeground(new java.awt.Color(102, 153, 255));
        element15.setText("The quick brown fox jumps over the lazy dog.");

        element5fld6.setBackground(new java.awt.Color(230, 230, 230));
        element5fld6.setFont(new getfont().getone(Font.BOLD,20f));
        element5fld6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 153, 255)));
        element5fld6.setFocusable(false);
        element5fld6.setMaximumSize(new java.awt.Dimension(0, 17));
        element5fld6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                controlfld(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                controlfld(evt);
            }
        });

        element16.setFont(new getfont().getone(Font.BOLD,16f));
        element16.setForeground(new java.awt.Color(102, 153, 255));
        element16.setText("The quick brown fox jumps over the lazy dog.");

        element6lbl7.setBackground(new java.awt.Color(230, 230, 230));
        element6lbl7.setFont(new getfont().getone(Font.BOLD,20f));
        element6lbl7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 153, 255)));
        element6lbl7.setFocusable(false);
        element6lbl7.setMaximumSize(new java.awt.Dimension(0, 17));
        element6lbl7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                controlfld(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                controlfld(evt);
            }
        });

        element19.setFont(new getfont().getone(Font.BOLD,16f));
        element19.setForeground(new java.awt.Color(102, 153, 255));
        element19.setText("The quick brown fox jumps over the lazy dog.");

        element9lbl10.setBackground(new java.awt.Color(230, 230, 230));
        element9lbl10.setFont(new getfont().getone(Font.BOLD,20f));
        element9lbl10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 153, 255)));
        element9lbl10.setFocusable(false);
        element9lbl10.setMaximumSize(new java.awt.Dimension(0, 17));
        element9lbl10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                controlfld(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                controlfld(evt);
            }
        });

        javax.swing.GroupLayout Group2Layout = new javax.swing.GroupLayout(Group2);
        Group2.setLayout(Group2Layout);
        Group2Layout.setHorizontalGroup(
            Group2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Group2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(Group2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Group2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(element9lbl10, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                        .addComponent(element6lbl7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(element5fld6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(element3fld4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Group2Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(Group2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(element13)
                                .addComponent(element15)
                                .addComponent(element16))
                            .addGap(305, 305, 305))
                        .addComponent(element1fld1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(element11)
                    .addComponent(element19))
                .addGap(100, 100, 100))
        );
        Group2Layout.setVerticalGroup(
            Group2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Group2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(element11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(element1fld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(element13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(element3fld4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(element15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(element5fld6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(element16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(element6lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(element19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(element9lbl10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        force.setBackground(new java.awt.Color(230, 230, 230));
        force.setForeground(new java.awt.Color(230, 230, 230));
        force.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forceMouseExited(evt);
            }
        });

        forcestop.setBackground(new java.awt.Color(204, 0, 51));
        forcestop.setToolTipText("Emergency stop");
        forcestop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forcestopMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forcestopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forcestopMouseExited(evt);
            }
        });

        javax.swing.GroupLayout forcestopLayout = new javax.swing.GroupLayout(forcestop);
        forcestop.setLayout(forcestopLayout);
        forcestopLayout.setHorizontalGroup(
            forcestopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        forcestopLayout.setVerticalGroup(
            forcestopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout forceLayout = new javax.swing.GroupLayout(force);
        force.setLayout(forceLayout);
        forceLayout.setHorizontalGroup(
            forceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forceLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(forcestop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        forceLayout.setVerticalGroup(
            forceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, forceLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(forcestop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Group2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(force, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Group2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(force, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(25, 35, 55));

        mytitle.setFont(new getfont().getone(55f));
        mytitle.setForeground(new java.awt.Color(255, 255, 255));
        mytitle.setText("Practice");

        jPanel3.setBackground(new java.awt.Color(25, 35, 55));

        Racordlbl.setFont(new getfont().getone(35f));
        Racordlbl.setForeground(new java.awt.Color(255, 255, 255));
        Racordlbl.setText("Records :");

        Errorelbl.setFont(new getfont().getone(35f));
        Errorelbl.setForeground(new java.awt.Color(255, 255, 255));
        Errorelbl.setText("Errors    :");

        Racordlbl1.setFont(new getfont().getone(35f));
        Racordlbl1.setForeground(new java.awt.Color(255, 255, 255));
        Racordlbl1.setText("0");

        errorlbl1.setFont(new getfont().getone(35f));
        errorlbl1.setForeground(new java.awt.Color(255, 255, 255));
        errorlbl1.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Racordlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Errorelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(errorlbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(Racordlbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 45, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Racordlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Errorelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Racordlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(errorlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(mytitle, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mytitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void controlfld(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_controlfld
        JTextField jf = (JTextField) getFocusOwner();
        if (jf.getText().length() == s1.length() && evt.getKeyChar() != 8) {
            if (jf.getText().equals(s1) && getFocusOwner()!=element9lbl10) {
                jf.getNextFocusableComponent().setFocusable(true);
                jf.getNextFocusableComponent().requestFocus();
                jf.setFocusable(false);
            } else if(jf.getText().equals(s1) && getFocusOwner()==element9lbl10)
            {
                int a=JOptionPane.showConfirmDialog(rootPane,"Do you want to do this practice again??", "Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,new ImageIcon(getClass().getResource("/icons8-ask_question.png")));                
                if(a==0)
                {
                    this.dispose();                    
                    new Practice3(s1,pra,record,error,ID,name2);
                }
                else
                {
                    if(!name2.equals("guest"))
                    {
                        save(ID);
                    }
                    this.dispose();
                    new alphabaticlist(ID,name2);
                    
                }                
            }
            else {
                if (jf.isEditable()) {
                    error++;
                    errorlbl1.setText(String.valueOf(error));
                }
            }
            jf.setEditable(false);
        } else {
            jf.setEditable(true);
        }
    }//GEN-LAST:event_controlfld

    private void forcestopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forcestopMouseEntered
        force.setBackground(new Color(25,35,55));
    }//GEN-LAST:event_forcestopMouseEntered

    private void forcestopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forcestopMouseExited
        force.setBackground(new Color(230,230,230));
    }//GEN-LAST:event_forcestopMouseExited

    private void forceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forceMouseClicked
        int a=JOptionPane.showConfirmDialog(rootPane,"Current Record will not be saved, Do you want to stop this Practice here??\nRemember, it can now or never..", "Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,new ImageIcon(getClass().getResource("/icons8-ask_question.png")));
        if(a==0)
        {
            if(!name2.equals("guest") && record>0)
                    {
                        record--;
                        save(ID);
                    }
            new alphabaticlist(ID, name2);
            this.dispose();
        }
    }//GEN-LAST:event_forceMouseClicked

    private void forceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forceMouseEntered
        force.setBackground(new Color(25,35,55));
    }//GEN-LAST:event_forceMouseEntered

    private void forceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forceMouseExited
        force.setBackground(new Color(230,230,230));
    }//GEN-LAST:event_forceMouseExited

    private void forcestopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forcestopMouseClicked
        int a=JOptionPane.showConfirmDialog(rootPane,"Current Record will not be saved, Do you want to stop this Practice here??\nRemember, it can now or never..", "Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,new ImageIcon(getClass().getResource("/icons8-ask_question.png")));
        if(a==0)
        {
            new alphabaticlist(ID, name2);
            this.dispose();
        }
    }//GEN-LAST:event_forcestopMouseClicked
    public void save(String ID)
    {               
        record++;
        String sql="insert into record values('"+ID+"','"+pra+"','"+record+"','"+error+"','"+DateTimeFormatter.ofPattern("dd/MM/yyyy  HH:mm:ss").format(LocalDateTime.now())+"');";                                    
        record--;
        try
        {
            Connection con = DriverManager.getConnection("jdbc:sqlite:Dataset.sqlite");
            Statement st=con.createStatement();  
            Class.forName("org.sqlite.JDBC");            
            st.executeUpdate(sql);                
            }
            catch(Exception e)
            {
                try
                {
                DriverManager.getConnection("jdbc:sqlite:Dataset.sqlite").createStatement().executeUpdate("create table record(ID varchar(20),Practice varchar(25),Records varchar(25),Errors varchar(25),datetime varchar(40));");
                DriverManager.getConnection("jdbc:sqlite:Dataset.sqlite").createStatement().executeUpdate(sql);                
                }
                catch(Exception ae)
                {
                    JOptionPane.showMessageDialog(rootPane,"Can not Save your record due to unknown error","Unknown Error",JOptionPane.ERROR_MESSAGE,new ImageIcon(getClass().getResource("/icons8_Close_Window_50px.png")));                                                      
                }
            }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Errorelbl;
    private javax.swing.JPanel Group2;
    private javax.swing.JLabel Racordlbl;
    private javax.swing.JLabel Racordlbl1;
    private javax.swing.JLabel element11;
    private javax.swing.JLabel element13;
    private javax.swing.JLabel element15;
    private javax.swing.JLabel element16;
    private javax.swing.JLabel element19;
    private javax.swing.JTextField element1fld1;
    private javax.swing.JTextField element3fld4;
    private javax.swing.JTextField element5fld6;
    private javax.swing.JTextField element6lbl7;
    private javax.swing.JTextField element9lbl10;
    private javax.swing.JLabel errorlbl1;
    private javax.swing.JPanel force;
    private javax.swing.JPanel forcestop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel mytitle;
    // End of variables declaration//GEN-END:variables
}
